
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: 99bigdaddy
      MYSQL_USER: 99bigdaddy
      MYSQL_PASSWORD: 99bigdaddy
      MYSQL_ROOT_PASSWORD: 99bigdaddy
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
