// Database Queries Index
export * from "./admin.queries";
export * from "./auth.queries";
export * from "./daily.queries";
export * from "./k3.queries";
export * from "./k5.queries";
export * from "./payment.queries";
export * from "./user.queries";
export * from "./wingo.queries";
